---
development:
  cloud_name: dfhpmevxm
  api_key: '921671124837634'
  api_secret: xM4-2uwGquxDXMGjB8O0zq-VWyM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dfhpmevxm
  api_key: '921671124837634'
  api_secret: xM4-2uwGquxDXMGjB8O0zq-VWyM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dfhpmevxm
  api_key: '921671124837634'
  api_secret: xM4-2uwGquxDXMGjB8O0zq-VWyM
  enhance_image_tag: true
  static_image_support: false
